name: heroSuper

gmail: "mailto:shantanup410@gmail.com"
instagram: "https://www.instagram.com/shawnp410/"
twitter: "https://twitter.com/ShantanuP41"
facebook: "https://www.facebook.com/shantanu.pawar.319247/"
youtube: "https://www.youtube.com/channel/UCV4nS5CwzFOKxOPXWYPWBFg"
linkedin: "https://www.linkedin.com/in/shawn-p-291000203/"
hashnode: "https://hashnode.com/@shantanuP41"
reddit: "https://www.reddit.com/user/shantanuP41"
tumblr: "https://www.tumblr.com/settings/blog/shawnp410"
quora: "https://www.quora.com/profile/Shantanu-Pawar-68"
github: "https://github.com/pawar41"
developers: "https://g.dev/shawnp"

baseurl: "heroSuper" 


markdown: kramdown
kramdown:
  input: GFM

title: heroSuper



